version: "3"

services:

  backend:
    container_name: ddd_backend
    build:
      context: projects/backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DDD_FORUM_APP_SECRET=${DDD_FORUM_APP_SECRET}
      - DDD_FORUM_REDIS_URL=ddd_forum_redis
      - DDD_FORUM_REDIS_PORT=6379
      - DDD_FORUM_DB_HOST=ddd_forum_mysql
      - DDD_FORUM_DB_DEV_DB_NAME=${DDD_FORUM_DB_DEV_DB_NAME}
    depends_on:
      - mysql
      - redis

  frontend:
    container_name: ddd_frontend
    build:
      context: projects/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  mysql:
    container_name: ddd_forum_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql:5.6.47
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_DATABASE=${DDD_FORUM_DB_DEV_DB_NAME}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DDD_FORUM_DB_PASS}

  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080

  redis:
    container_name: ddd_forum_redis
    image: redis:latest
    ports:
      - 6379:6379
